name: Android CI

on:
   push:
     branches: [ "dev" ]
   pull_request:
     branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - run: echo "VERSION_SUFFIX=-$(echo $GITHUB_SHA | cut -c 1-9)" >> $GITHUB_ENV

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY }}
          ENCODED_PROPS: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > keystore.jks
          echo $ENCODED_PROPS | base64 -di > keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleEmulatorRelease

      - name: rename
        run: |
          filenames=`ls app/build/outputs/apk/emulator/release/*.apk`
          for eachfile in $filenames
          do
            newpath=${eachfile%.*};
            mv $eachfile ${newpath%-*}.apk
          done

      - name: Path lister action
        uses: Rishabh510/Path-lister-action@1.0
        id: pl
        with:
          path: "app/build/outputs/apk/emulator/release"
          type: ".apk"

      - name: Split Action
        uses: JungWinter/split@v2.0.0
        id: split
        with:
          msg: ${{ steps.pl.outputs.paths }}
          separator: ' '

      - name: list filenames
        id: filenames
        run: |
          echo "::set-output name=name0::"$(basename ${{ steps.split.outputs._0 }} .apk)
          echo "::set-output name=name1::"$(basename ${{ steps.split.outputs._1 }} .apk)
          echo "::set-output name=name2::"$(basename ${{ steps.split.outputs._2 }} .apk)
          echo "::set-output name=name3::"$(basename ${{ steps.split.outputs._3 }} .apk)
          echo "::set-output name=name4::"$(basename ${{ steps.split.outputs._4 }} .apk)

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.name0 }}
          path: ${{ steps.split.outputs._0 }}
          retention-days: 14

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.name1 }}
          path: ${{ steps.split.outputs._1 }}
          retention-days: 14

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.name2 }}
          path: ${{ steps.split.outputs._2 }}
          retention-days: 14

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.name3 }}
          path: ${{ steps.split.outputs._3 }}
          retention-days: 14

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.name4 }}
          path: ${{ steps.split.outputs._4 }}
          retention-days: 14

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: symbols
          path: |
            app/build/outputs/mapping
            app/build/outputs/native-debug-symbols
          retention-days: 14

#      - name: Draft GitHub Release
#        uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.REPO_TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: true
#          draft: true
#          files: |
#            ${{ steps.split.outputs._0 }}
#            ${{ steps.split.outputs._1 }}
#            ${{ steps.split.outputs._2 }}
#            ${{ steps.split.outputs._3 }}
#            ${{ steps.split.outputs._4 }}
