name: Android CI

on: workflow_dispatch
#   push:
#     branches: [ "dev" ]
#   pull_request:
#     branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleEmulatorRelease
      
    - uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/emulator/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
#       env:
        # override default build-tools version (29.0.3) -- optional
#         BUILD_TOOLS_VERSION: "33.0.0"

    - name: Path lister action
      uses: Rishabh510/Path-lister-action@1.0
      id: pl
      with:
        path: "./app/build/outputs/apk/emulator/release"
        type: "-signed.apk"

    - name: Example Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.REPO_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        draft: true
        files: |
          ${{ steps.pl.outputs.paths }}
